# Generated by Django 5.0.4 on 2024-04-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0004_likenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Numbercomment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
