# Generated by Django 5.0.4 on 2024-04-23 07:26

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0006_remove_news_numbercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Img1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='profile/'),
        ),
    ]
