# Generated by Django 5.0.4 on 2024-04-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0007_alter_doctor_img1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
    ]
