# Generated by Django 5.0.4 on 2024-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0008_remove_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daywork',
            name='name',
            field=models.IntegerField(choices=[(4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday')]),
        ),
    ]
