# Generated by Django 5.0.4 on 2024-05-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0010_rename_name_daywork_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdoctor',
            name='time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentdoctor',
            name='Date',
            field=models.DateField(),
        ),
    ]
