# Generated by Django 5.0.6 on 2024-05-16 10:08

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0011_appointmentdoctor_time_alter_appointmentdoctor_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('Des', models.CharField(max_length=300)),
                ('Img1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='profile/')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointmentclinic',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='appointmentdoctor',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='daywork',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Des',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Img1',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='Des',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='Img1',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='specialization',
        ),
        migrations.AddField(
            model_name='daywork',
            name='Employ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Day_Employee', to='centerapp.employ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='employ_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centerapp.employ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='employ_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centerapp.employ'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FaDoctor',
        ),
    ]
