# Generated by Django 5.0.6 on 2024-05-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0012_employ_remove_appointmentclinic_therapist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer_doctor', to='centerapp.doctor'),
            preserve_default=False,
        ),
    ]
