# Generated by Django 5.0.6 on 2024-05-16 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0013_offer_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentclinic',
            name='therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Appointmentservice_therapist', to='centerapp.therapist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentdoctor',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_Doctor', to='centerapp.doctor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FaDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faDoctor_Doctor', to='centerapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faDoctor_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
