# Generated by Django 5.0.6 on 2024-05-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0014_appointmentclinic_therapist_appointmentdoctor_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentclinic',
            name='Date',
        ),
    ]
