# Generated by Django 5.0.6 on 2024-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0015_remove_appointmentclinic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentclinic',
            name='Date',
            field=models.DateField(default='2020-12-7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentclinic',
            name='time',
            field=models.TimeField(default='11:11:11'),
            preserve_default=False,
        ),
    ]
