# Generated by Django 5.0.6 on 2024-05-17 06:08

import centerapp.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0017_location_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Img1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=centerapp.models.upload_to),
        ),
    ]
