# Generated by Django 5.0.6 on 2024-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0020_clinic_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_created=True, default='2002-01-01 11:11:11'),
            preserve_default=False,
        ),
    ]
