# Generated by Django 5.0.6 on 2024-05-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0021_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
