# Generated by Django 5.0.6 on 2024-05-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0024_doctor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
