# Generated by Django 5.0.6 on 2024-05-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0026_fathei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='loction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loction_about', to='centerapp.location'),
        ),
    ]
