# Generated by Django 5.0.6 on 2024-05-17 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerapp', '0027_alter_about_loction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Des', models.CharField(max_length=100)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CONew', to='centerapp.news')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CoNews_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
