# Generated by Django 5.0.4 on 2024-04-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_address_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Manager', 'Manager'), ('Recption', 'Recption')], max_length=20, null=True),
        ),
    ]
